# Generated by Django 3.2.4 on 2022-05-27 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PicUploadView',
            new_name='UploadImage',
        ),
    ]
